name: Run test on PR merge
on:
  push:
    branches:
      - '*'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for gh-pages

      # Step 2: Set up JDK 17 using Adoptium (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install Maven
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      # Step 4: Install Allure
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      # Step 5: Cache Maven dependencies to speed up the build process
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 6: Run Tests
      - name: Run Tests
        run: mvn clean test verify

      # Step 7: Upload Test Results and Reports as Artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/
            allure-results/
            reports/
          retention-days: 2  # Adjust retention as needed

      # Step 8: Load Test Report History (Ensure correct branch fetching)
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: report
          path: report
          fetch-depth: 0

      # Step 9: Build Test Report
      - name: Build test report
        if: always()
        run: |
          allure generate reports/allure-results --clean -o report/allure-history

      # Step 10: Publish Test Report
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report
          publish_dir: report/allure-history