name: Run test on PR merge
on:
  push:
    branches:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Oracle JDK 17
      - name: Install Oracle JDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget --no-check-certificate -q https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
          sudo mkdir -p /usr/lib/jvm
          sudo tar -xzf jdk-17_linux-x64_bin.tar.gz -C /usr/lib/jvm
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-17/bin/java 1
          sudo update-alternatives --config java
          java -version

      # Step 3: Cache Maven dependencies to speed up the build process
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Dependencies using Maven
      - name: Install Dependencies
        run: mvn clean install

      # Step 5: Build Project (Use mvn package if you want to build an artifact)
      - name: Build Project
        run: mvn package

      # Step 6: Run Tests
      - name: Run Tests
        run: mvn clean test verify