name: On Code Push Any Branch
on:
  push:
    branches:
      - '*'

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 using Adoptium (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Step 3: Install Maven (Windows)
      - name: Install Maven
        run: choco install maven -y

      # Step 4: Install Allure (Windows)
      - name: Install Allure
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install allure
          $allurePath = $(scoop prefix allure) + "\bin"
          if (-Not (Test-Path $allurePath)) {
            Write-Host "Allure installation directory not found!"
            exit 1
          }
          echo $allurePath | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      # Step 5: Cache Maven dependencies to speed up the build process
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 6: Run Tests
      - name: Run Tests
        run: mvn clean test verify

      # Step 7: Upload Test Results and Reports as Artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/
            allure-report/
            reports/
          retention-days: 2  # Adjust retention as needed

      # Step 8: Load Test Report History
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Step 9: Build Test Report
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      # Step 10: Publish Test Report
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history