name: Run test on PR merge
on:
  push:
    branches:
      - '*'

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 using Adoptium (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Step 3: Install Maven (Windows)
      - name: Install Maven
        run: choco install maven -y

      # Step 4: Install Allure (Windows)
      - name: Install Allure
        run: |
          Invoke-WebRequest -Uri "https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip" -OutFile "allure.zip"
          Expand-Archive -Path allure.zip -DestinationPath "C:\allure"
          echo "C:\allure\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH
          echo "C:\allure\bin" >> $GITHUB_PATH
          $env:Path += ";C:\allure\bin"
          Get-ChildItem -Path "C:\allure\bin"
          allure --version
          
          # Step 5: Cache Maven dependencies to speed up the build process
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 6: Run Tests
      - name: Run Tests
        run: mvn clean test verify

      # Step 7: Upload Test Results and Reports as Artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/
            allure-report/
            reports/
          retention-days: 2  # Adjust retention as needed