name: Run test on PR merge
on:
  push:
    branches:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 using Adoptium (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'  # This replaces 'adoptopenjdk'

      # Step 3: Install Maven
      - name: Install Maven
        run: sudo apt-get install -y maven

      # Step 4: Cache Maven dependencies to speed up the build process
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Run Tests
      - name: Run Tests
        run: mvn clean test verify